- shell:
  -
    command: touch ~/.hushlogin
    description: Disable "last login" prompt when opening a shell
  -
    command: brew install hcloud
    description: Hetzner Cloud CLI
  -
    command: brew install hashicorp/tap/terraform hashicorp/tap/terraform-ls
    description: Terraform
  -
    command: brew install --cask docker
    description: Docker
  -
    command: brew install kubectl int128/kubelogin/kubelogin helm openlens k9s
    description: Kubernetes
  -
    command: brew install mas keycastr shortcat skhd yabai
    description: Macos tools
  -
    command:
    - brew install jq gh most parallel git-filter-repo pandoc netcat nmap fswatch
    description: Basic utilities
  -
    command:
    - brew tap homebrew/cask-fonts
    - brew install --cask font-hack-nerd-font
    description: Fonts
  -
    command: brew install so tldr task knqyf263/pet/pet
    description: Information related
  -
    command:
    # Disable Keyboard -> Shortcuts -> Mission Control -> Move left/right a space.
    - defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 79 "{enabled = 0; value = { parameters = (65535, 123, 8650752); type = standard;};}"
    - defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 80 "{enabled = 0; value = { parameters = (65535, 123, 8781824); type = standard;};}"
    - defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 81 "{enabled = 0; value = { parameters = (65535, 124, 8650752); type = standard;};}"
    - defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 82 "{enabled = 0; value = { parameters = (65535, 124, 8781824); type = standard;};}"
    # Ask the system to read the hotkey plist file and ignore the output. Likely updates an in-memory cache with the new plist values.
    - defaults read com.apple.symbolichotkeys.plist > /dev/null
    # Run reactivateSettings to apply the updated settings.
    - /System/Library/PrivateFrameworks/SystemAdministration.framework/Resources/activateSettings -u
