- shell:
   - setup/cleanup.sh ~/.config/nvim

- clean: ['~/.config/nvim']

- link:
    ~/.config/nvim:
      create: true
      path: neovim

- shell:
    -
      command: install_nvim
      description: Checking nvim
      stdout: true
      stderr: true
