- shell:
   - setup/cleanup.sh ~/.config/nvim

- clean: ['~/.config/nvim']

- link:
    ~/.config/nvim:
      create: true
      path: neovim

- shell:
    -
      command: zsh -c "install_nvim"
      description: Checking nvim
      stdout: true
      stderr: true
    -
      command: nvim --headless "+Lazy! sync" +qa
      description: Install, cleanup and update neovim plugins
      stdout: true
      stderr: true
