- clean: ['~/.config/nvim']

- create:
    - ~/.local/share/nvim/site/pack/packer/start

- link:
    ~/.config/nvim:
      create: true
      path: neovim

- shell:
    -
      command: setup/neovim.sh
      description: Checking nvim
      stdout: true
      stderr: true
