- clean: ['~/.nodenv']

- link:
    ~/.nodenv: node/nodenv
    ~/.nodenv/plugins/node-build:
      create: true
      path: node/node-build
    ~/.nodenv/plugins/nodenv-default-packages:
      create: true
      path: node/nodenv-default-packages
    ~/.nodenv/default-packages:
      create: true
      path: node/default-packages

- shell:
  -
    command: setup/nodejs.sh
    description: Checking nodejs environment
    stdout: true
    stderr: true
  -
    command: which node | grep shims
    description: Checking node path
    stdout: true
    stderr: true
  -
    command: node --version
    description: Checking node version
    stdout: true
    stderr: true
  -
    command: npm list -g | grep neovim
    description: Checking node packages
    stdout: true
    stderr: true
