- link:
    ~/.nodenv: node/nodenv
    ~/.nodenv/plugins/node-build:
      create: true
      path: node/node-build
    ~/.nodenv/plugins/nodenv-default-packages:
      create: true
      path: node/nodenv-default-packages
    ~/.nodenv/default-packages:
      create: true
      path: node/default-packages

- shell:
  -
    command: setup/nodejs.sh
    description: Checking nodejs environment
    stdout: true
    stderr: true
