- link:
    ~/.nodenv: node/nodenv
    ~/.nodenv/plugins/node-build:
      create: true
      path: node/node-build

- shell:
  -
    command: setup/nodejs.sh
    description: Checking nodejs environment
    stdout: true
    stderr: true
