- clean: ['~/.rbenv']

- link:
    ~/.rbenv: ruby/rbenv
    ~/.rbenv/plugins/ruby-build:
      create: true
      path: ruby/ruby-build

- shell:
  -
    command: setup/ruby.sh
    description: Checking ruby environment
    stdout: true
    stderr: true
  -
    command: which ruby | grep shims
    description: Checking ruby path
    stdout: true
    stderr: true
  -
    command: ruby --version
    description: Checking ruby version
    stdout: true
    stderr: true
  -
    command: gem list | grep neovim
    description: Checking ruby packages
    stdout: true
    stderr: true
