- clean: ['~/.config/nvim', '~/.config/coc']

- create:
    - ~/.local/share/nvim/plugged

- shell:
    - setup/cleanup.sh ~/.config/nvim/coc-settings.json

- link:
    ~/.config/nvim/init.vim:
      create: true
      path: vim/init.vim
    ~/.local/share/nvim/site/autoload/plug.vim:
      create: true
      path: vim/vim-plug/plug.vim
    ~/.vim/autoload/plug.vim:
      create: true
      path: vim/vim-plug/plug.vim
    ~/vimwiki: vimwiki
    ~/.config/nvim/coc-settings.json: vim/coc-settings.json

- shell:
    -
      command: setup/nvim.sh
      description: Checking nvim
      stdout: true
      stderr: true
