- create:
    - ~/.zsh_history_dir

- shell:
    - setup/cleanup.sh ~/.zshenv ~/.zshrc ~/.p10k.zsh ~/.config/pet
    - register-python-argcomplete pipx > ~/.zfunc/_pipx
    - rustup completions zsh cargo > ~/.zfunc/_cargo
    - rustup completions zsh > ~/.zfunc/_rustup
    - pip completion --zsh > ~/.zfunc/_pip
    - oc completion zsh > ~/.zfunc/_oc
    - docker completion zsh > ~/.zfunc/_docker
    - podman completion -f ~/.zfunc/_podman zsh

- link:
    ~/.zshenv: zsh/zshenv
    ~/.zshrc: zsh/zshrc
    ~/.p10k.zsh: zsh/p10k.zsh
    ~/.config/pet:
      create: true
      path: pet
