- create:
    - ~/.zsh_history_dir

- shell:
    - setup/cleanup.sh ~/.zshrc ~/.config/pet

- link:
    ~/.zshenv: zsh/zshenv
    ~/.zshrc: zsh/zshrc
    ~/.config/pet:
      create: true
      path: pet
