# Generic hardware configuration
# This file should be replaced with your actual hardware-configuration.nix
# generated by `nixos-generate-config`

{ config, pkgs, lib, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # NOTE: Replace this with your actual hardware configuration
  # Run `nixos-generate-config` to generate the correct values

  # Example boot configuration (UEFI)
  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ]; # or kvm-amd for AMD
  boot.extraModulePackages = [ ];

  # Example filesystem configuration
  # Replace with your actual UUIDs from `blkid`
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/REPLACE-WITH-YOUR-UUID";
    fsType = "ext4";
    # Or for btrfs:
    # fsType = "btrfs";
    # options = [ "subvol=@" "compress=zstd" "noatime" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/REPLACE-WITH-YOUR-BOOT-UUID";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  # Swap configuration
  swapDevices = [
    # { device = "/dev/disk/by-uuid/REPLACE-WITH-SWAP-UUID"; }
    # Or use zram swap (recommended)
  ];

  # Enable zram swap (compressed RAM swap)
  zramSwap = {
    enable = true;
    memoryPercent = 50;
    algorithm = "zstd";
  };

  # CPU microcode updates
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # For AMD:
  # hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Enable firmware for hardware
  hardware.enableRedistributableFirmware = true;
  hardware.enableAllFirmware = true;

  # Graphics
  hardware.graphics = {
    enable = true;
    enable32Bit = true;
    # For NVIDIA (uncomment and configure if needed):
    # extraPackages = with pkgs; [
    #   nvidia-vaapi-driver
    #   vaapiVdpau
    #   libvdpau-va-gl
    # ];
  };

  # For NVIDIA GPUs (uncomment if applicable):
  # services.xserver.videoDrivers = [ "nvidia" ];
  # hardware.nvidia = {
  #   modesetting.enable = true;
  #   powerManagement.enable = false;
  #   open = false;
  #   nvidiaSettings = true;
  #   package = config.boot.kernelPackages.nvidiaPackages.stable;
  # };

  # For AMD GPUs (uncomment if applicable):
  # boot.initrd.kernelModules = [ "amdgpu" ];

  # Platform (detected automatically, but can be set explicitly)
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
