[[snippets]]
  description = "Get hostname by IP address"
  command = "nbtstat -a <IP address>"
  output = ""

[[snippets]]
  description = "Show SMART status for all disks"
  command = "lsblk -o name -d -n -p | sudo parallel --tag smartctl -H {} | awk '/result/ { print$1\" \"$7 }'"
  output = ""

[[snippets]]
  description = "Find what package a file belongs to"
  command = "dpkg -S <filename>"
  output = ""

[[snippets]]
  description = "Indicate how a command would be interpreted. Like \"which\" but more detailed."
  command = "type <command>"
  output = ""

[[snippets]]
  description = "One-line summary of what a command does"
  command = "whatis <command>"
  output = ""

[[snippets]]
  description = "List files that belong to a package"
  command = "dpkg -L <package>"
  output = ""

[[snippets]]
  description = "List windows managed by the window manager and include WM_CLASS in the list."
  command = "wmctrl -l -x"
  output = ""

[[snippets]]
  description = "Extend logical volume and resize the filesystem to fit the new size."
  command = "lvextend --size +<extend_amount> <device> && resize2fs <device>"
  output = ""

[[snippets]]
  description = "Discover DHCP servers on the network."
  command = "sudo nmap --script broadcast-dhcp-discover"
  output = ""

[[snippets]]
  description = "List local ports that are listening and the related user and process."
  command = "sudo netstat -lepunt"
  output = ""

[[snippets]]
  description = "Mount using sshfs"
  command = "sshfs <hostname>:<srcpath> <destpath>"
  output = ""

[[snippets]]
  description = "Unmount sshfs mount"
  command = "fusermount -u <mountpath>"
  output = ""

[[snippets]]
  description = "List hosts scanned on the network that we were able to resolve the hostnames of. Format output in tabbed columns."
  command = "nmap -sL -R 172.26.11-15.0-255 -oG - | awk '$3 != \"()\" { print $1, $2, $3 }' | column -t"
  output = ""

[[snippets]]
  description = "Show list of files installed by a package"
  command = "pacman -Ql <package_name>"
  output = ""

[[snippets]]
  description = "Show Power_On_Hours for all disks."
  command = "lsblk -o name -d -n -p | sudo parallel --tag smartctl -A {} | awk '/Power_On_Hours/ { print $1, $3\":\", $11 }'"
  output = ""

[[snippets]]
  description = "List model of all hard drives."
  command = "lsblk -o name -d -n -p | sudo parallel --tag hdparm -i {} | grep Model"
  output = ""

[[snippets]]
  description = "Run short self-test on all disks"
  command = "lsblk -o name -d -n -p | sudo parallel --tag smartctl -t short {}"
  output = ""

[[snippets]]
  description = "Generate random string for use as a salt, password etc."
  command = "openssl rand -base64 32"
  output = ""

[[snippets]]
  description = "List reverse dependencies; packages that depend or recommend the specified package."
  command = "apt-cache rdepends --installed <package_name>"
  output = ""

[[snippets]]
  description = "Fuzzy-search through all available packages, with package info shown in a preview window, and then install selected packages."
  command = "pacman -Slq | fzf --multi --preview 'pacman -Si {1}' | xargs -ro sudo pacman -S"
  output = ""

[[snippets]]
  description = "Fuzzy-search through all available packages, with package info and file list shown in a preview window, and then install selected packages (make sure you run pacman -Fy at least once before invocation to sync the pacman file database)."
  command = "pacman -Slq | fzf --multi --preview 'cat <(pacman -Si {1}) <(pacman -Fl {1} | awk \"{print \\$2}\")' | xargs -ro sudo pacman -S"
  output = ""

[[snippets]]
  description = "Show swap usage of all processes sorted by usage in a pager"
  command = "for file in /proc/*/status ; do awk '/VmSwap|Name/{printf $2 \" \" $3}END{ print \"\"}' $file; done | sort -k 2 -n -r | less"
  output = ""

[[snippets]]
  description = "Show package dependencies and which packages it is required by."
  command = "pacman -Qi <package_name>"
  output = ""

[[snippets]]
  description = "List orphan packages."
  command = "pacman -Qtd"
  output = ""

[[snippets]]
  description = "Create a dependency graph of a package."
  command = "pactree -g <package_name> | dot -Tsvg -o <package_name>-deps.svg"
  output = ""

[[snippets]]
  description = "List packages installed from AUR."
  command = "pacman -Qm"
  output = ""

[[snippets]]
  description = "Scan the ed25519 fingerprint of a remote server and append it to the known_hosts file of the local machine."
  command = "ssh-keyscan -H -t ed25519 <ip_address> >> ~/.ssh/known_hosts"
  output = ""

[[snippets]]
  description = "Flush DNS cache on macos"
  command = "sudo dscacheutil -flushcache;sudo killall -HUP mDNSResponder"
  output = ""

[[snippets]]
  description = "Show log messages from a process of a certain type and time period on macos."
  command = "log show --predicate 'process == \"<process_name>\" && messageType == \"<message_type>\"' --last <time_period>"
  output = ""

[[snippets]]
  description = "Add monitoring enabled label to all servers in active Hetzner project."
  command = "hcloud server list -o columns=name -o noheader | parallel hcloud server add-label {} monitoring=enabled"
  output = ""

[[snippets]]
  description = "Use hcloud to list server names and labels"
  command = "hcloud server list --output columns=name,labels"
  output = ""
