-- This file is intentionally left empty or contains non-plugin configurations.
-- Plugin definitions are automatically loaded by lazy.nvim from individual files
-- in this directory (e.g., `plugins/telescope.lua`, `plugins/treesitter.lua`).
return {
  -- You can add non-plugin specific configurations here if needed,
  -- or configurations that need to be loaded before other plugins.

  -- Example commented-out plugins from original file:
  -- "folke/which-key.nvim",
  -- "tpope/vim-speeddating",
  -- "tpope/vim-eunuch",
  -- "tpope/vim-rhubarb",
  -- {
  --   'altermo/ultimate-autopair.nvim',
  --   event = { 'InsertEnter', 'CmdlineEnter' },
  --   branch = 'v0.6',   --recommended as each new version will have breaking changes
  --   opts = {
  --     --Config goes here
  --   },
  -- }
  -- {
  --   "nvimtools/none-ls.nvim",
  --   dependencies = {
  --     "nvimtools/none-ls-extras.nvim",
  --   },
  --   config = function()
  --     local null_ls = require("null-ls")
  --
  --     null_ls.setup({
  --       sources = {
  --         null_ls.builtins.formatting.stylua,
  --         null_ls.builtins.completion.spell,
  --         require("none-ls.formatting.jq"),
  --         require("none-ls.diagnostics.eslint"), -- requires none-ls-extras.nvim
  --       },
  --     })
  --   end,
  -- },
}
