- link:
    ~/.default-python-packages: default-python-packages
    ~/.default-npm-packages: default-npm-packages
    ~/.default-cargo-crates: default-cargo-crates
    ~/.default-golang-pkgs: default-golang-pkgs
    ~/.tool-versions: .tool-versions
    ~/.asdfrc: .asdfrc

- shell:
    -
      command: |
        # asdf update
        asdf plugin update --all
        # Cache asdf plugin short names in the background
        asdf plugin list-all > /dev/null &
        # Install plugins
        asdf plugin add python
        asdf plugin add nodejs
        asdf plugin add rust
        asdf plugin add golang
        asdf plugin add fzf
        asdf plugin add neovim
        asdf plugin add direnv
        asdf plugin add pdm
        # install configured tool versions
        asdf uninstall neovim
        asdf install
      description: asdf setup
      stdout: true
      stderr: true
    -
      command: "$(asdf where fzf)/install --completion --key-bindings --no-update-rc --no-bash --no-fish"
      description: Generate fzf configuration
      stdout: true
      stderr: true
    -
      command: |
        brew install groff autoconf
        source ./zsh/fzf-tab/fzf-tab.zsh
        build-fzf-tab-module
      description: Build fzf-tab binary for colorization
      stdout: true
      stderr: true
