- shell:
  - command: git config --global pull.rebase true
    stdout: true
    stderr: true
    description: "Set pull to always rebase instead of merge"
  - command: git config --global init.defaultBranch main
    stdout: true
    stderr: true
    description: "Set the default branch for new repositories to 'main'"
  - command: git config --global filter.lfs.clean 'git-lfs clean -- %f'
    stdout: true
    stderr: true
    description: "Configure LFS filter for cleaning files"
  - command: git config --global filter.lfs.smudge 'git-lfs smudge -- %f'
    stdout: true
    stderr: true
    description: "Configure LFS filter for smudging files"
  - command: git config --global filter.lfs.process 'git-lfs filter-process'
    stdout: true
    stderr: true
    description: "Configure LFS filter for processing files"
  - command: git config --global filter.lfs.required true
    stdout: true
    stderr: true
    description: "Make LFS filter required for the repository"
  - command: git config --global rebase.autoStash true
    stdout: true
    stderr: true
    description: "Automatically stash changes before rebasing"
  - command: git config --global rebase.autosquash true
    stdout: true
    stderr: true
    description: "Automatically squash commits during rebase"
  - command: git config --global core.pager delta
    stdout: true
    stderr: true
    description: "Use 'delta' as the pager for viewing diffs and logs"
  - command: git config --global interactive.diffFilter 'delta --color-only'
    stdout: true
    stderr: true
    description: "Use 'delta' to filter diffs in interactive mode"
  - command: git config --global delta.navigate true
    stdout: true
    stderr: true
    description: "Enable navigation between diff sections in 'delta'"
  - command: git config --global delta.light false
    stdout: true
    stderr: true
    description: "Set 'delta' to use dark theme (suitable for light terminal backgrounds)"
  - command: git config --global merge.conflictstyle diff3
    stdout: true
    stderr: true
    description: "Use diff3 conflict style for merges"
  - command: git config --global merge.ff only
    stdout: true
    stderr: true
    description: "Only allow fast-forward merges"
  - command: git config --global diff.colorMoved zebra
    stdout: true
    stderr: true
    description: "Use zebra coloring for moved code in diffs"
  - command: git config --global diff.algorithm histogram
    stdout: true
    stderr: true
    description: "Use histogram diff algorithm"
  - command: git config --global rerere.enabled true
    stdout: true
    stderr: true
    description: "Enable reuse recorded resolution of conflicted merges"
  - command: git config --global rerere.autoupdate true
    stdout: true
    stderr: true
    description: "Automatically update rerere database"
  - command: git config --global push.default current
    stdout: true
    stderr: true
    description: "Push the current branch by default"
  - command: git config --global push.autoSetupRemote true
    stdout: true
    stderr: true
    description: "Automatically set up remote for new branches"
  - command: git config --global color.ui auto
    stdout: true
    stderr: true
    description: "Enable colored output"
  - command: git config --global log.date iso
    stdout: true
    stderr: true
    description: "Use ISO 8601 date format for logs"
  - command: git config --global help.autocorrect 20
    stdout: true
    stderr: true
    description: "Enable autocorrection for Git commands"
