- create:
    - ~/.i3

- shell:
    - setup/cleanup.sh ~/.config/dunst/dunstrc ~/.xinitrc ~/.Xresources

- link:
    ~/.xinitrc: X/xinitrc
    ~/.Xresources: X/Xresources
    ~/i3blocks-contrib: i3/i3blocks-contrib
    ~/.i3blocks.conf: i3/i3blocks.conf
    ~/.config/dunst/dunstrc:
      create: true
      path: i3/dunstrc

- shell:
    -
      command: setup/i3.sh
      description: Checking i3
      stdout: true
      stderr: true
