- shell:
  -
    command: touch ~/.hushlogin
    description: Disable "last login" prompt when opening a shell
  -
    command: brew bundle
    description: Install and update packages defined in the Brewfile
  -
    command:
    # Disable Keyboard -> Shortcuts -> Mission Control -> Move left/right a space.
    - defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 79 "{enabled = 0; value = { parameters = (65535, 123, 8650752); type = standard;};}"
    - defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 80 "{enabled = 0; value = { parameters = (65535, 123, 8781824); type = standard;};}"
    - defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 81 "{enabled = 0; value = { parameters = (65535, 124, 8650752); type = standard;};}"
    - defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 82 "{enabled = 0; value = { parameters = (65535, 124, 8781824); type = standard;};}"
    # Ask the system to read the hotkey plist file and ignore the output. Likely updates an in-memory cache with the new plist values.
    - defaults read com.apple.symbolichotkeys.plist > /dev/null
    # Run reactivateSettings to apply the updated settings.
    - /System/Library/PrivateFrameworks/SystemAdministration.framework/Resources/activateSettings -u
