- shell:
   - setup/cleanup.sh ~/.config/nvim

- clean: ['~/.config/nvim']

- link:
    ~/.config/nvim:
      create: true
      path: neovim

- shell:
    -
      command: nvim --headless "+Lazy! sync" "+MasonUpdate" +qa
      description: Install, cleanup and update neovim plugins
      stdout: true
      stderr: true
    # The checkhealth just runs forever
    # -
    #   command: nvim --headless "+checkhealth" +qa
    #   description: Check neovim health
    #   stdout: true
    #   stderr: true
