- create:
    - ~/.zsh_history_dir
    - ~/.config/atuin

- shell:
    - setup/cleanup.sh ~/.zshenv ~/.zshrc ~/.config/pet
    - touch ~/.api_tokens
    - if command -v pipx; then pipx install argcomplete && register-python-argcomplete pipx > ~/.zfunc/_pipx; fi
    - if command -v rustup; then rustup completions zsh cargo > ~/.zfunc/_cargo; fi
    - if command -v rustup; then rustup completions zsh > ~/.zfunc/_rustup; fi
    - if command -v pip; then pip completion --zsh > ~/.zfunc/_pip; fi
    - if command -v oc; then oc completion zsh > ~/.zfunc/_oc; fi
    - if command -v docker; then docker completion zsh > ~/.zfunc/_docker; fi
    - if command -v podman; then podman completion -f ~/.zfunc/_podman zsh; fi
    - if command -v rpk; then rpk generate shell-completion zsh > ~/.zfunc/_rpk; fi
    - if command -v kubectl; then kubectl completion zsh > ~/.zfunc/_kubectl; fi
    - if command -v pdm; then pdm completion zsh > ~/.zfunc/_pdm; fi
    - if command -v npm; then npm completion zsh > ~/.zfunc/_npm; fi
    - if command -v luarocks; then luarocks completion zsh > ~/.zfunc/_luarocks; fi
    - if command -v minikube; then minikube completion zsh > ~/.zfunc/_minikube; fi
    - if command -v atuin; then atuin gen-completions --shell zsh --out-dir ~/.zfunc; fi
    - if command -v k3d; then k3d completion zsh > ~/.zfunc/_k3d; fi
    - if command -v gh; then gh completion -s zsh > ~/.zfunc/_gh; fi
    - if command -v argocd; then argocd completion zsh > ~/.zfunc/_argocd; fi
    - if command -v rg; then rg --generate=complete-zsh > ~/.zfunc/_rg; fi
    - if command -v helm; then helm completion zsh > ~/.zfunc/_helm; fi
    - if command -v mise; then mise completion zsh > ~/.zfunc/_mise; fi
    - if command -v arduino-cli; then arduino-cli completion zsh > ~/.zfunc/_arduino-cli; fi

- link:
    ~/.zshenv: zsh/zshenv
    ~/.zshrc: zsh/zshrc
    ~/.config/pet:
      create: true
      path: pet
    ~/.config/starship.toml: starship.toml
    ~/.config/atuin/config.toml: atuin-config.toml
