#!/bin/bash

# Merge colors and settings
xrdb ~/.Xresources

# Force KDE environment when running i3
export QT_QPA_PLATFORMTHEME="qt5ct"
export QT_PLUGIN_PATH=$HOME/.kde4/lib/kde4/plugins/:/usr/lib/kde4/plugins/
# XDG_CURRENT_DESKTOP=kde
export DESKTOP_SESSION=kde

# Create i3 config from base and local
cat $HOME/.dotfiles/i3/config.base \
    $HOME/.dotfiles/i3/config.local > $HOME/.i3/config

exec /usr/bin/dbus-launch --exit-with-session i3
