#!/bin/bash

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

export QT_QPA_PLATFORMTHEME="qt5ct"

$HOME/.dotfiles/i3/build-config.sh

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# eval $(/usr/bin/gnome-keyring-daemon -s --components=pkcs11,secrets,ssh,gpg)
# export SSH_AUTH_SOCK

session=${1:-i3}

case $session in
    i3   ) exec i3;;
    *    ) exec $1;;
esac
