#!/usr/bin/env bash
# Simple, robust Claude CLI completion generator
# This script creates zsh completion by using a more straightforward parsing approach

set -euo pipefail

# Colors and formatting
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly BLUE='\033[0;34m'
readonly NC='\033[0m'

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly DOTFILES_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
readonly COMPLETION_FILE="${DOTFILES_DIR}/dot_zfunc/_claude"

log() { echo -e "${BLUE}[$(date +'%H:%M:%S')]${NC} $*" >&2; }
error() { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }
success() { echo -e "${GREEN}[SUCCESS]${NC} $*" >&2; }

check_claude_cli() {
    if ! command -v claude >/dev/null 2>&1; then
        error "Claude CLI not found in PATH"
    fi
    log "Found claude CLI: $(claude --version 2>/dev/null | head -1 || echo 'unknown version')"
}

# awk program that turns a `--help` "Commands:" block into TAB-separated
# `name<TAB>description` records. Handles the three shapes the Claude CLI
# emits: argument specs after the name (`attach <id>`, `import [options]
# [source]`), descriptions wrapped across continuation lines, and alias
# names (`plugin|plugins`) that must become one completion candidate each.
# shellcheck disable=SC2016  # awk program text; $0/$1 are awk fields, not shell
readonly AWK_PARSE_COMMANDS='
function flush(   n, i, parts) {
    if (cmd == "") return
    gsub(/[ \t]+/, " ", desc)
    sub(/^ +/, "", desc)
    sub(/ +$/, "", desc)
    n = split(cmd, parts, "|")
    for (i = 1; i <= n; i++) printf "%s\t%s\n", parts[i], desc
    cmd = ""
    desc = ""
    desccol = 0
}
/^Commands:/ && !inblock { inblock = 1; next }
!inblock { next }
# Any unindented line starts a new help section and ends the command block.
/^[^ \t]/ { flush(); inblock = 0; next }
/^[ \t]*$/ { next }
{
    # A command entry is indented exactly two spaces and separates its name
    # from its description with a run of two or more spaces.
    if ($0 ~ /^  [A-Za-z0-9]/) {
        rest = substr($0, 3)
        if (match(rest, /  +/)) {
            flush()
            cmd = substr(rest, 1, RSTART - 1)
            sub(/ .*$/, "", cmd)          # drop `[options]` / `<id>` arg specs
            desc = substr(rest, RSTART + RLENGTH)
            desccol = 2 + RSTART + RLENGTH
            next
        }
        next
    }
    # A continuation line is indented at least as far as the description
    # column, which is what separates wrapped text from embedded examples.
    if (cmd != "") {
        match($0, /^ */)
        if (RLENGTH >= desccol - 1) {
            line = $0
            sub(/^ +/, "", line)
            desc = desc " " line
        }
    }
}
END { flush() }
'

# Read a "Commands:" block on stdin and emit zsh `_describe` array entries,
# quoting each field so apostrophes in descriptions cannot terminate the
# surrounding zsh single-quoted string.
parse_commands() {
    awk "$AWK_PARSE_COMMANDS" | while IFS=$'\t' read -r cmd desc; do
        printf "        '%s:%s'\n" "${cmd//\'/\'\\\'\'}" "${desc//\'/\'\\\'\'}"
    done
}

# Print a subcommand's help, or nothing when the subcommand does not exist.
# An unknown subcommand makes the Claude CLI fall back to the top-level help,
# which would otherwise be harvested as if it were the subcommand's own.
subcommand_help() {
    local sub="$1" out
    out=$(claude "$sub" --help 2>/dev/null) || return 0
    grep -q "^Usage: claude ${sub} " <<<"$out" || return 0
    printf '%s\n' "$out"
}

# Generate the complete zsh completion file: a static skeleton with the
# command lists extracted from the CLI's own `--help` output.
generate_completion() {
    log "Generating updated Claude CLI completion..."

    mkdir -p "$(dirname "$COMPLETION_FILE")"

    local main_commands config_commands mcp_commands
    main_commands=$(claude --help 2>/dev/null | parse_commands)
    config_commands=$(subcommand_help config | parse_commands)
    mcp_commands=$(subcommand_help mcp | parse_commands)

    [[ -n "$main_commands" ]] || error "No commands found in 'claude --help' output"
    [[ -n "$mcp_commands" ]] || error "No commands found in 'claude mcp --help' output"

    # Build into a temporary file so a failed validation never leaves a
    # broken completion behind in the source tree.
    local tmp
    tmp=$(mktemp "${TMPDIR:-/tmp}"/_claude.XXXXXX)

cat > "$tmp" << 'COMPLETION_EOF'
#compdef claude

# Zsh completion for Claude Code CLI
# Auto-generated by scripts/generate-claude-completion-simple.sh
# Maintained as part of chezmoi dotfiles configuration

_claude() {
    local -a commands
    local context state state_descr line
    typeset -A opt_args

    commands=(
COMPLETION_EOF

    printf '%s\n' "$main_commands" >> "$tmp"

cat >> "$tmp" << 'COMPLETION_EOF'
    )

    _arguments -C \
        '--add-dir[Additional directories to allow tool access to]:directories:_files -/' \
        '--agent[Agent for the current session]:agent:' \
        '--agents[JSON object defining custom agents]:json:' \
        '--allow-dangerously-skip-permissions[Enable bypassing permissions as an option without it being default]' \
        '--allowedTools[Comma or space-separated list of tool names to allow]:tools:' \
        '--allowed-tools[Comma or space-separated list of tool names to allow]:tools:' \
        '--append-system-prompt[Append a system prompt to the default system prompt]:prompt:' \
        '--betas[Beta headers to include in API requests (API key users only)]:betas:' \
        '--chrome[Enable Claude in Chrome integration]' \
        '(-c --continue)'{-c,--continue}'[Continue the most recent conversation]' \
        '--dangerously-skip-permissions[Bypass all permission checks]' \
        '(-d --debug)'{-d,--debug}'[Enable debug mode with optional category filter]:filter:' \
        '--debug-file[Write debug logs to a specific file path]:path:_files' \
        '--disable-slash-commands[Disable all skills]' \
        '--disallowedTools[Comma or space-separated list of tool names to deny]:tools:' \
        '--disallowed-tools[Comma or space-separated list of tool names to deny]:tools:' \
        '--effort[Effort level for the current session]:level:(low medium high xhigh max)' \
        '--fallback-model[Enable automatic fallback to specified model (only with --print)]:model:_claude_models' \
        '--file[File resources to download at startup (file_id:relative_path)]:specs:' \
        '--fork-session[When resuming, create a new session ID instead of reusing the original]' \
        '--from-pr[Resume a session linked to a PR by PR number/URL, or open interactive picker]:pr:' \
        '(-h --help)'{-h,--help}'[Display help for command]' \
        '--ide[Automatically connect to IDE on startup if exactly one valid IDE is available]' \
        '--include-partial-messages[Include partial message chunks as they arrive (--print --output-format=stream-json only)]' \
        '--input-format[Input format (only with --print)]:format:(text stream-json)' \
        '--json-schema[JSON Schema for structured output validation]:schema:' \
        '--max-budget-usd[Maximum dollar amount to spend on API calls (only with --print)]:amount:' \
        '--mcp-config[Load MCP servers from JSON files or strings]:configs:_files' \
        '--mcp-debug[DEPRECATED. Use --debug instead. Enable MCP debug mode]' \
        '--model[Model for the current session]:model:_claude_models' \
        '--no-chrome[Disable Claude in Chrome integration]' \
        '--no-session-persistence[Disable session persistence (only with --print)]' \
        '--output-format[Output format (only with --print)]:format:(text json stream-json)' \
        '--permission-mode[Permission mode to use for the session]:mode:(acceptEdits auto bypassPermissions default dontAsk plan)' \
        '--plugin-dir[Load plugins from directories for this session only]:paths:_files -/' \
        '(-p --print)'{-p,--print}'[Print response and exit (useful for pipes)]' \
        '--replay-user-messages[Re-emit user messages from stdin back on stdout (stream-json only)]' \
        '(-r --resume)'{-r,--resume}'[Resume a conversation by session ID, or open interactive picker]:sessionId:' \
        '--session-id[Use a specific session ID for the conversation]:uuid:' \
        '--setting-sources[Comma-separated list of setting sources to load]:sources:' \
        '--settings[Path to a settings JSON file or a JSON string]:file:_files' \
        '--strict-mcp-config[Only use MCP servers from --mcp-config]' \
        '--system-prompt[System prompt to use for the session]:prompt:' \
        '--tmux[Create a tmux session for the worktree (requires --worktree)]' \
        '--tools[Specify available tools from the built-in set]:tools:' \
        '--verbose[Override verbose mode setting from config]' \
        '(-v --version)'{-v,--version}'[Output the version number]' \
        '(-w --worktree)'{-w,--worktree}'[Create a new git worktree for this session]:name:' \
        '1: :->command' \
        '*: :->args' && return 0

    case $state in
        command)
            _describe -t commands 'claude commands' commands
            ;;
        args)
            case $words[1] in
COMPLETION_EOF

    if [[ -n "$config_commands" ]]; then
cat >> "$tmp" << 'COMPLETION_EOF'
                config)
                    _claude_config
                    ;;
COMPLETION_EOF
    fi

cat >> "$tmp" << 'COMPLETION_EOF'
                mcp)
                    _claude_mcp
                    ;;
                install)
                    _claude_install
                    ;;
                *)
                    _message 'prompt text'
                    ;;
            esac
            ;;
    esac
}
COMPLETION_EOF

    if [[ -n "$config_commands" ]]; then
cat >> "$tmp" << 'COMPLETION_EOF'

_claude_config() {
    local -a config_commands
    config_commands=(
COMPLETION_EOF

    printf '%s\n' "$config_commands" >> "$tmp"

cat >> "$tmp" << 'COMPLETION_EOF'
    )

    _arguments -C \
        '(-h --help)'{-h,--help}'[Display help for command]' \
        '1: :->subcommand' \
        '*: :->args' && return 0

    case $state in
        subcommand)
            _describe -t config-commands 'config commands' config_commands
            ;;
        args)
            case $words[2] in
                get)
                    _arguments \
                        '(-g --global)'{-g,--global}'[Use global config]' \
                        '1:key:_claude_config_keys'
                    ;;
                set)
                    _arguments \
                        '(-g --global)'{-g,--global}'[Use global config]' \
                        '1:key:_claude_config_keys' \
                        '2:value:'
                    ;;
                remove|rm)
                    _arguments \
                        '(-g --global)'{-g,--global}'[Use global config]' \
                        '1:key:_claude_config_keys' \
                        '*:values:'
                    ;;
                list|ls)
                    _arguments \
                        '(-g --global)'{-g,--global}'[Use global config]'
                    ;;
                add)
                    _arguments \
                        '(-g --global)'{-g,--global}'[Use global config]' \
                        '1:key:_claude_config_keys' \
                        '*:values:'
                    ;;
            esac
            ;;
    esac
}
COMPLETION_EOF
    fi

cat >> "$tmp" << 'COMPLETION_EOF'

_claude_mcp() {
    local -a mcp_commands
    mcp_commands=(
COMPLETION_EOF

    printf '%s\n' "$mcp_commands" >> "$tmp"

cat >> "$tmp" << 'COMPLETION_EOF'
    )

    _arguments -C \
        '(-h --help)'{-h,--help}'[Display help for command]' \
        '1: :->subcommand' \
        '*: :->args' && return 0

    case $state in
        subcommand)
            _describe -t mcp-commands 'mcp commands' mcp_commands
            ;;
        args)
            case $words[2] in
                serve)
                    _arguments \
                        '(-d --debug)'{-d,--debug}'[Enable debug mode]' \
                        '--verbose[Override verbose mode setting from config]'
                    ;;
                add)
                    _arguments \
                        '(-s --scope)'{-s,--scope}'[Configuration scope]:scope:(local user project)' \
                        '(-t --transport)'{-t,--transport}'[Transport type]:transport:(stdio sse http)' \
                        '(-e --env)'{-e,--env}'[Set environment variables]:env:' \
                        '(-H --header)'{-H,--header}'[Set WebSocket headers]:header:' \
                        '1:name:' \
                        '2:commandOrUrl:' \
                        '*:args:'
                    ;;
                remove)
                    _arguments \
                        '(-s --scope)'{-s,--scope}'[Configuration scope]:scope:(local user project)' \
                        '1:name:_claude_mcp_servers'
                    ;;
                get)
                    _arguments \
                        '1:name:_claude_mcp_servers'
                    ;;
                add-json)
                    _arguments \
                        '(-s --scope)'{-s,--scope}'[Configuration scope]:scope:(local user project)' \
                        '1:name:' \
                        '2:json:'
                    ;;
                add-from-claude-desktop)
                    _arguments \
                        '(-s --scope)'{-s,--scope}'[Configuration scope]:scope:(local user project)'
                    ;;
            esac
            ;;
    esac
}

_claude_install() {
    local -a install_targets
    install_targets=(
        'stable:Install stable version'
        'latest:Install latest version'
    )

    _arguments \
        '--force[Force installation even if already installed]' \
        '(-h --help)'{-h,--help}'[Display help for command]' \
        '1: :->target' && return 0

    case $state in
        target)
            _describe -t install-targets 'install targets' install_targets
            _message 'or specific version'
            ;;
    esac
}

# Helper function to complete model names
_claude_models() {
    local -a models
    models=(
        'fable:Latest Fable model (Fable 5.1; not a plan default — select explicitly)'
        'best:Latest Fable where available, else latest Opus'
        'opus:Latest Opus model (Opus 5)'
        'sonnet:Latest Sonnet model (Sonnet 5)'
        'haiku:Latest Haiku model (Haiku 4.5)'
        'opusplan:Plan with Opus, execute with the session default model'
        'default:Default model for the session'
        'claude-fable-5-1:Claude Fable 5.1'
        'claude-opus-5:Claude Opus 5'
        'claude-sonnet-5:Claude Sonnet 5'
        'claude-haiku-4-5:Claude Haiku 4.5'
    )
    _describe -t models 'claude models' models
}

COMPLETION_EOF

    if [[ -n "$config_commands" ]]; then
cat >> "$tmp" << 'COMPLETION_EOF'
# Helper function to complete config keys
_claude_config_keys() {
    local -a config_keys
    config_keys=(
        'theme:UI theme setting'
        'allowedTools:Allowed tool names'
        'disallowedTools:Disallowed tool names'
        'hasTrustDialogAccepted:Trust dialog acceptance status'
        'hasCompletedProjectOnboarding:Project onboarding status'
        'permissionMode:Default permission mode'
        'model:Default model'
        'fallbackModel:Fallback model'
    )
    _describe -t config-keys 'config keys' config_keys
}

COMPLETION_EOF
    fi

cat >> "$tmp" << 'COMPLETION_EOF'
# Helper function to complete MCP server names
_claude_mcp_servers() {
    local -a servers
    # Try to get actual server names, fallback to common ones
    if command -v claude >/dev/null 2>&1; then
        servers=(${(f)"$(claude mcp list 2>/dev/null | grep -E '^[a-zA-Z0-9_-]+:' | cut -d: -f1)"})
    fi

    # Fallback to common server names if the command fails
    if [[ ${#servers} -eq 0 ]]; then
        servers=(
            'playwright:Playwright MCP server'
            'context7:Context7 MCP server'
            'github:GitHub MCP server'
            'pal:PAL MCP server'
            'vectorcode:VectorCode MCP server'
            'graphiti-memory:Graphiti Memory MCP server'
            'sequential-thinking:Sequential Thinking MCP server'
            'sentry:Sentry MCP server'
        )
    fi
    _describe -t mcp-servers 'MCP servers' servers
}

_claude "$@"
COMPLETION_EOF

    # Validate before publishing, so a syntax error never lands in the source
    # tree. zsh's own diagnostic is the only thing that names the bad line.
    # Keep the rejected output outside the chezmoi source tree: any file in
    # dot_zfunc/ becomes a managed target on the next apply.
    if ! zsh -n "$tmp"; then
        error "Generated completion has syntax errors; kept for inspection at $tmp"
    fi

    mv "$tmp" "$COMPLETION_FILE"
    success "Updated Claude CLI completion: $COMPLETION_FILE"
}

main() {
    log "Starting Claude CLI completion generation (simple version)"
    check_claude_cli
    generate_completion

    # Add to git if not tracked
    if ! git -C "$DOTFILES_DIR" ls-files --error-unmatch "$COMPLETION_FILE" >/dev/null 2>&1; then
        log "Adding completion file to git..."
        git -C "$DOTFILES_DIR" add "$COMPLETION_FILE"
        success "Added completion file to git tracking"
    fi

    success "Claude CLI completion generation complete!"
    echo
    echo "To use the updated completion:"
    echo "  1. Reload your shell: exec zsh"
    echo "  2. Or source the completion: source $COMPLETION_FILE"
    echo "  3. Test with: claude <TAB>"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
