PATH=""

# Append "$1" to $PATH when not already in.
# This function API is accessible to scripts in /etc/profile.d
append_path () {
    case ":$PATH:" in
        *:"$1":*)
            ;;
        *)
            PATH="${PATH:+$PATH:}$1"
    esac
}

# Append our default paths
append_path "$HOME/perl5/bin"
append_path "$HOME/.rbenv/bin"
append_path "$HOME/.rbenv/shims"
append_path "$HOME/.cargo/bin"
append_path "$HOME/.local/bin"
append_path "$HOME/go/bin"
append_path '/usr/local/go/bin'
append_path '/usr/local/sbin'
append_path '/usr/local/bin'
append_path '/usr/bin'
append_path '/bin'

export PATH

# Load profiles from /etc/profile.d
if test -d /etc/profile.d/; then
        for profile in /etc/profile.d/*.sh; do
                test -r "$profile" && . "$profile"
        done
        unset profile
fi

unset -f append_path

# Define these to install perl modules without root
# For neovim perl module
# https://metacpan.org/pod/local::lib
PERL5LIB="/home/lgates/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/home/lgates/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/home/lgates/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/home/lgates/perl5"; export PERL_MM_OPT;

# Disable python keyring, so pip install won't pop open annoying dialogs
PYTHON_KEYRING_BACKEND="keyring.backends.null.Keyring"; export PYTHON_KEYRING_BACKEND;

# set terminal preference for i3
export TERMINAL=kitty

# set browser preference
export BROWSER=google-chrome-stable

if command -v nvim >/dev/null 2>&1; then
    export EDITOR='nvim'
    export VISUAL='nvim'
    export SUDO_EDITOR='nvim'
else
    export EDITOR='vim'
    export VISUAL='vim'
    export SUDO_EDITOR='vim'
fi

# Set default umask
umask 022

# No need to source ruby or nvm here, because the zsh plugins already do that!

# Use ripgrep for faster performance
# Do not respect vcs ignore files such as .gitignore, since it's nice to be able
# to open up CakePHP source files for example for reference
export FZF_DEFAULT_COMMAND="rg --files --hidden"
# export FZF_DEFAULT_COMMAND="rg --files --hidden --no-ignore-vcs"
export FZF_PREVIEW_COMMAND="bat --style=numbers,changes --wrap never --color always {} || cat {} || tree -C {}"
export FZF_CTRL_T_OPTS="--min-height 30 --preview-window down:60% --preview-window noborder --preview '($FZF_PREVIEW_COMMAND) 2> /dev/null'"

# Preview directory tree when using Alt+C
export FZF_ALT_C_OPTS="--preview 'tree -C {} | head -200'"

# for existing man pages
function fzf_apropos() {
  apropos '' | fzf --preview-window=up:50% --preview 'echo {} | cut -f 1 -d " " | xargs man' | cut -f 1 -d " "
}

# Fix SDL full screen output to correct monitor
export SDL_VIDEO_FULLSCREEN_HEAD=0

# vim:ft=sh
