# http://blog.askesis.pl/post/2017/04/how-to-debug-zsh-startup-time.html
# uncomment this and zprof at the end of this file to profile zsh startup
#zmodload zsh/zprof

#if [ "$XDG_CURRENT_DESKTOP" = "KDE" ] || [ "$XDG_CURRENT_DESKTOP" = "GNOME" ]; then
#  ZSH_TMUX_AUTOSTART="true"
#fi

#emulate sh -c '. /etc/profile'

# https://www.reddit.com/r/zsh/comments/jncp79/paste_bracketing_causes_slow_pastes/
DISABLE_MAGIC_FUNCTIONS=true

# https://www.johnhawthorn.com/2012/09/vi-escape-delays/
KEYTIMEOUT=1

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="agnoster"
DISABLE_AUTO_UPDATE="true"
COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="dd.mm.yyyy"
HISTFILE="$HOME/.zsh_history_dir/$(hostname -f)"

# vim mode cursor styling
MODE_CURSOR_VIINS="#7e7 blinking bar"
MODE_CURSOR_REPLACE="$MODE_CURSOR_VIINS #f55"
MODE_CURSOR_VICMD="#3a3 block"
MODE_CURSOR_SEARCH="#d4d steady underline"
MODE_CURSOR_VISUAL="$MODE_CURSOR_VICMD steady bar"
MODE_CURSOR_VLINE="$MODE_CURSOR_VISUAL #3ee"

# https://github.com/ohmyzsh/ohmyzsh/pull/9090
ZSH_COMPDUMP="${ZSH_CACHE_DIR}/.zcompdump-${SHORT_HOST}-${ZSH_VERSION}"

# User configuration
export DEFAULT_USER="$USER"
# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
export LANG="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"
# export LC_ALL="en_US.UTF-8"

# kitty
# autoload -Uz compinit
# compinit

# https://grml.org/zsh/zsh-lovers.html
# Fuzzy matching of completions for when you mistype them:
zstyle ':completion:*' completer _complete _match _approximate
zstyle ':completion:*:match:*' original only
zstyle ':completion:*:approximate:*' max-errors 1 numeric
# cd will never select the parent directory (e.g.: cd ../<TAB>):
zstyle ':completion:*:cd:*' ignore-parents parent pwd

# fzf-tab related styles
# disable sort when completing `git checkout`
zstyle ':completion:*:git-checkout:*' sort false
# set descriptions format to enable group support
zstyle ':completion:*:descriptions' format '[%d]'
# set list-colors to enable filename colorizing
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
# preview directory's content with exa when completing cd
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'exa -1 --color=always $realpath'
# switch group using `,` and `.`
zstyle ':fzf-tab:*' switch-group ',' '.'

# nodenv completions
[ -f ~/.nodenv/completions/nodenv.zsh ] && source ~/.nodenv/completions/nodenv.zsh

# rbenv completions
[ -f ~/.rbenv/completions/rbenv.zsh ] && source ~/.rbenv/completions/rbenv.zsh

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
#
# NOTE: fzf-tab needs to be loaded after compinit, but before plugins which
# will wrap widgets, such as zsh-autosuggestions or fast-syntax-highlighting!!
# Since oh-my-zsh runs compinit, the relevant thing here is that the plugins
# are in the correct order.
plugins=(
  fzf-tab
  git gh
  extract
  zsh-autosuggestions zsh-syntax-highlighting
  z systemd
  colored-man-pages
  pip python virtualenv pyenv
  cake composer
  nmap taskwarrior
  npm yarn
  ruby gem bundler
  fd ripgrep
  docker docker-compose
  rust
  kubectl
  terraform
)

##### Fix tmux key mappings
# Fix Home/End keys
bindkey "\e[1~" beginning-of-line
bindkey "\e[4~" end-of-line

# Delete/Insert keys
bindkey "\e[3~" delete-char
bindkey "\e[2~" quoted-insert

# Mac binds
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word

# Add a PC-like bind for pipe on macos
# command + < is similar to Alt Gr + <
bindkey -s "^[[60;9u" "|"

# mappings for "page up" and "page down" to step to the beginning/end
# of the history
# bindkey "\e[5~" beginning-of-history
# bindkey "\e[6~" end-of-history

# alternate mappings for "page up" and "page down" to search the history
# bindkey "\e[5~" history-search-backward
# bindkey "\e[6~" history-search-forward

# mappings for Ctrl-left-arrow and Ctrl-right-arrow for word moving
# bindkey "\e[1;5C" forward-word
# bindkey "\e[1;5D" backward-word
# bindkey "\e[5C" forward-word
# bindkey "\e[5D" backward-word
# bindkey "\e\e[C" forward-word
# bindkey "\e\e[D" backward-word

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

prompt_context() {
  if [[ "$USER" != "$DEFAULT_USER" || -n "$SSH_CLIENT" ]]; then
      prompt_segment black default "%(!.%{%F{yellow}%}.)$USER@$(hostname -f)"
  fi
}

# Disable non-breaking space
# This doesn't seem to work when set via xprofile
# if [[ ! -z $DISPLAY ]]; then
#     setxkbmap -layout "fi" -variant "nodeadkeys" -option "nbsp:none"
# fi

# Oh-my-zsh needs to be loaded after plugins and such have been defined.
# Otherwise plugins and completions will not be loaded.
source $ZSH/oh-my-zsh.sh

# Should check if fzf is installed?
# Has to be loaded after oh-my-zsh or Ctrl+T & Alt+C keybinds don't work among other things
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Completion for kitty
# The kitty docs specify that this has to be called after compinit
# compinit is called by oh-my-zsh, so this has to be after sourcing oh-my-zsh
# https://sw.kovidgoyal.net/kitty/index.html#configuring-kitty
if type kitty > /dev/null; then
    kitty + complete setup zsh | source /dev/stdin
fi

#zprof
