# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
    fi
fi

# load common environment configuration
source ~/.env

# environment configuration

# write host history in separate files
export HISTFILE="${HOME}/.bash_history/$(hostname -f)"

# set vim as default editor
export EDITOR=vim
export VISUAL=vim

# set vi -mode for bash
#set -o vi
